// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/veleton777/booking_api/internal/booking/v1/booking/entity"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// SaveBooking provides a mock function with given fields: _a0, _a1
func (_m *Storage) SaveBooking(_a0 context.Context, _a1 entity.Booking) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Booking) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
